#+TITLE: ELEC 343 Assignment 3
#+AUTHOR: Jasper Chan - 37467164

#+OPTIONS: num:3

#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage{steinmetz}
#+LATEX_HEADER: \usepackage{siunitx}
#+LATEX_HEADER: \DeclareSIUnit\inch{in}
#+LATEX_HEADER: \DeclareSIUnit\ounce{oz}
#+LATEX_HEADER: \DeclareSIUnit\rpm{rpm}
#+LATEX_HEADER: \DeclareSIUnit\hp{hp}
#+LATEX_HEADER: \usepackage{tikz}
\sisetup{inter-unit-product=\cdot}
* Example 3B
** SP3.4-1
A 12-V, permanent-magnet dc motor has an armature resistance of $\SI{12}{\ohm}$ and $k_v = \SI{0.01}{\volt\second/\radian}$.
Calculate the steady-state stall torque ($T_e$ with $\omega_r = 0$).
*** Solution
At stall, $E_a = 0$ and so all the current goes through the armature resistance.
\begin{align*}
I_a &= \frac{\SI{12}{\volt}}{\SI{12}{\ohm}} \\
&= \SI{1}{\ampere}
\end{align*}

From this we can calculate $T_e$

\begin{align*}
T_e &= k_v \cdot I_a \\
&= (\SI{0.01}{\volt\second/\radian}) \cdot (\SI{1}{\ampere}) \\
&= \SI{0.01}{\newton\meter}
\end{align*}
** SP3.4-1
Determine T_e in Example 3B.
*** Solution
From the textbook:
\begin{align*}
T_L &= \SI{3.53}{\milli\newton\meter} \\
B_m &= \SI{6.04}{\micro\newton\metre\second} \\
\omega_r &= \SI{249}{\radian/\second}
\end{align*}

From this we can calculate $T_e$
\begin{align*}
T_e &= B_m \omega_r + T_L \\
&= (\SI{6.04}{\micro\newton\metre\second})(\SI{249}{\radian/\second}) + (\SI{3.53}{\milli\newton\meter}) \\
&= \SI{5.053}{\milli\newton\meter} \\
&= \SI{0.713}{\ounce\inch}
\end{align*}
** SP3.6-2
What would happen to the rotor speed if, during field weakening, the field current accidentally become zero?
Why?
*** Solution
From Figure (3.6-1) in the textbook:
$$\omega_{r_{max}} = \frac{V_a}{k_v}$$

Since $k_v$ is proportional to field current, if it went to zero $\omega_{r_{max}} \rightarrow \infty$ and the machine would continually speed up until it destroyed itself.
* Textbook Chapter 3 Problems
** Problem 1
A permanent-magnet dc motor has the following parameters: $r_a = \SI{8}{\ohm}$ and $k_v = \SI{0.01}{\volt\second/\radian}$. 
The shaft load torque is approximated as $T_L = K \omega_r$, where $K = \SI{5}{\micro\meter\second}$.
The applied voltage is \SI{6}{\volt} and $B_m = 0$. Calculate the steady-state rotor speed $\omega_r$ in rad/s.
*** Solution
From the problem:

\begin{align*}
T_L &= k_t I_a \approx K \omega_r \\
I_a &\approx \frac{K \omega_r }{k_t}
\end{align*}

Subbing into $V$ and solving for $\omega_r$:

\begin{align*}
V &= \frac{K \omega_r}{k_v} r_a + \omega_r k_v \\
\omega_r &= \frac{V k_v}{K r_a + k_v^2} \\
&= \frac{(\SI{6}{\volt})(\SI{0.01}{\volt\second/\radian})}{(\SI{5}{\micro\meter\second})(\SI{8}{\ohm}) + (\SI{0.01}{\volt\second/\radian})^2} \\
&= \SI{428.6}{\radian/\second}
\end{align*}





** Problem 2
A permanent-magnet dc motor is driven by a mechanical source at \SI{3820}{\rpm}.
The measured open-circuit armature voltage is \SI{7}{\volt}.
The mechanical source is disconnected, and a \SI{12}{\volt} electric source is connected to the armature.
With zero-load torque, $I_a = \SI{0.1}{\ampere}$ and $\omega_r = \SI{650}{\radian/\second}$. Calculate $k_v$, $B_m$, and $r_a$
*** Solution
First we find $\omega_r$
\begin{align*}
\omega_r &= n \cdot \frac{\pi}{30} \\
&= (3820) \cdot \frac{\pi}{30} \\
&= \SI{400.03}{\radian/\second}
\end{align*}

When the motor is measured open-circuit, $I_a = 0$.
$$V_a = k_v \omega_{r_\text{driven}}$$

Solving for $k_v$ yields:

\begin{align*}
k_v &= \frac{V_a}{\omega_{r_\text{driven}}} \\
&= \frac{(\SI{7}{\volt})}{(\SI{400.03}{\radian/\second})} \\
&= \SI{0.0175}{\volt\second/\radian}
\end{align*}

At steady-state no-load operation:
$$T_e = B_m \omega_r = k_v I_a$$

Solving for $B_m$ yields:
\begin{align*}
B_m &= \frac{k_v I_a}{\omega_r} \\
&= \frac{(\SI{0.0175}{\volt\second/\radian})(\SI{0.1}{\ampere})}{(\SI{650}{\radian/\second})}
&= \SI{2.692}{\micro\newton\meter\second}
\end{align*}

The voltage across $r_a$ is
$$V_a - k_v \omega_r$$
Dividing by steady-state current to find resistance:

\begin{align*}
r_a &= \frac{V_a - k_v \omega_r}{I_a} \\
&= \frac{(\SI{12}{\volt}) - (\SI{0.0175}{\volt\second/\radian})(\SI{650}{\radian/\second})}{(\SI{0.1}{\ampere})} \\
&= \SI{6.25}{\ohm}
\end{align*}




** Problem 7
A dc machine is rated \SI{5}{\hp} with $V_f = \SI{240}{\volt}$, $V_a = \SI{240}{\volt}$, $r_a = \SI{0.63}{\ohm}$, and $L_{AF} = \SI{1.8}{\henry}$.
At rated conditions $\omega_r = \SI{127.7}{\radian/\second}$ and the total resistance of the field circuit is \SI{240}{\ohm}. \\
(a) Calculate the rated armature current.
The machine is to be operated in the constant-power mode beyond rated speed. \\
(b) Calculate I_f at four times rated speed. \\
(c) Calculate the boundary value of T_e for (b)
*** Solution
**** (a)
First let's calculate the rated field current $I_{fR}$
\begin{align*}
I_{fR} &= \frac{V_f}{r_f} \\
&= \frac{(\SI{240}{\volt})}{(\SI{240}{\ohm})} \\
&= \SI{1}{\ampere}
\end{align*}

Let's convert \SI{5}{\hp} to something more sensible.
\begin{align*}
P_{oR} &= (\SI{5}{\hp}) \cdot \frac{\SI{745.7}{\watt}}{\SI{1}{\hp}} \\
&= \SI{3727.5}{\watt}
\end{align*}

Now we can solve for rated torque
\begin{align*}
T_{eR} &= \frac{P_{oR}}{\omega_{rR}} \\
&= \frac{(\SI{3727.5}{\watt})}{(\SI{127.7}{\radian/\second})} \\
&= \SI{29.19}{\newton\meter}
\end{align*}

With this we can find the rated armature current
\begin{align*}
I_{aR} &= \frac{T_{eR}}{L_{AF} I_{fR}} \\
&= \frac{(\SI{29.19}{\newton\meter})}{(\SI{1.8}{\henry})(\SI{1}{\ampere})} \\
&= \SI{16.22}{\ampere}
\end{align*}
**** (b)
\begin{align*}
I_f &= \frac{P_{oR}}{L_{AF} \omega_r I_{aR}} \\
&= \frac{(\SI{3727.5}{\watt})}{(\SI{1.8}{\henry})\left(4\cdot(\SI{127.7}{\radian/\second})\right)(\SI{16.22}{\ampere})} \\
&= \SI{0.250}{\ampere}
\end{align*}
**** (c)
\begin{align*}
T_e &= L_{AF} I_{aR} I_f \\
&= (\SI{1.8}{\henry})(\SI{16.22}{\ampere})(\SI{0.250}{\ampere}) \\
&= \SI{7.30}{\newton\meter}
\end{align*}






* Additional Problems
** Problem A
Consider a \SI{100}{\volt} series DC motor.
The motor consumes \SI{100}{\watt} at full load while operating at speed of \SI{2000}{\rpm} when it is supplied from nominal voltage of \SI{100}{\volt}.

The armature and field winding resistances are: $R_a = \SI{2}{\ohm}$ and $R_f = \SI{1}{\ohm}$, respectively.
Calculate the stall torque (or the maximum starting torque) of this motor.
*** Solution
First we find the steady state current in the motor.
\begin{align*}
I_a &= \frac{P_\text{in}}{V_a} \\
&= \frac{\SI{100}{\watt}}{\SI{100}{\volt}} \\
&= \SI{1}{\ampere}
\end{align*}

Let's also find $\omega_r$
\begin{align*}
\omega_r &= (2000)\frac{\pi}{30} \\
&= \SI{209.44}{\radian/\second}
\end{align*}

Next we can rearrange the voltage equation to find the mutual inductance
\begin{align*}
V_a &= (R_a + R_f)I_a + \omega_r L_{AF} I_a \\
L_{AF} &= \frac{V_a - (R_a + R_f)I_a}{\omega_r I_a} \\
&= \frac{(\SI{100}{\volt}) - ((\SI{2}{\ohm}) + (\SI{1}{\ohm}))(\SI{1}{\ampere})}{(\SI{209.44}{\radian/\second})(\SI{1}{\ampere})}\\
&= \SI{0.463}{\henry}
\end{align*}

For $\omega_r = 0$ (stalling), the current  can be found using:
\begin{align*}
I_a &= \frac{V_a}{R_a + R_f} \\
&= \frac{(\SI{100}{\volt})}{(\SI{2}{\ohm}) + (\SI{1}{\ohm})} \\
&= \SI{33.33}{\ampere}
\end{align*}

The stall torque can then be found by
\begin{align*}
T_e &= L_{AF} I_a^2 \\
&= (\SI{0.463}{\henry})(\SI{33.33}{\ampere})^2 \\
&= \SI{514.34}{\newton\meter}
\end{align*}
** Problem B
Develop the time-domain block diagram for a series-connected dc machine.
You will also need this for Part 2 of this Assignment.

*** Solution
#+ATTR_LATEX: :placement [H]
#+CAPTION: Block diagram of a series DC motor. label:series_bd
[[./ProblemB.svg]]
* Series and PMDC Motor Analysis
#+BEGIN_SRC ipython :results silent :exports none
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
from matplotlib import pyplot as plt
import numpy as np
from pandas import DataFrame
import csv
#+END_SRC
** Block Diagrams
*** PMDC Motor
#+ATTR_LATEX: :placement [H]
#+CAPTION: Block diagram of a permanent magnet DC motor. label:pm_bd
[[./pm_motor.svg]]
*** Series DC Motor
See Figure ref:series_bd

** Transient Study
#+BEGIN_SRC ipython :results silent :exports none
series_data = {
    'time': [],
    'I_a': [],
    'omega_r': [],
    'T_e': []
}

pm_data = {
    'time': [],
    'I_a': [],
    'omega_r': [],
    'T_e': []
}

with open('./series_data.csv', 'r') as csvfile:
    plots = csv.reader(csvfile, delimiter=',')
    next(plots, None) # Skip header
    for row in plots:
        series_data['time'].append(float(row[0]))
        series_data['I_a'].append(float(row[1]))
        series_data['omega_r'].append(float(row[2]))
        series_data['T_e'].append(float(row[3]))
        
with open('./pm_data.csv', 'r') as csvfile:
    plots = csv.reader(csvfile, delimiter=',')
    next(plots, None) # Skip header
    for row in plots:
        pm_data['time'].append(float(row[0]))
        pm_data['I_a'].append(float(row[1]))
        pm_data['omega_r'].append(float(row[2]))
        pm_data['T_e'].append(float(row[3]))

#+END_SRC

#+BEGIN_SRC ipython :results silent :exports none

f, axarr = plt.subplots(3, sharex=True, figsize=(6, 8))

for ax in axarr.flat:
    ax.set(xlabel='t [s]')
# Hide x labels and tick labels for top plots and y ticks for right plots.
for ax in axarr.flat:
    ax.label_outer()

axarr[0].set_ylabel('$I_a$ [A]')
axarr[1].set_ylabel('$\omega_r$ [rad/s]')
axarr[2].set_ylabel('$T_e$ [$N \cdot m$]')

axarr[0].plot(series_data['time'], series_data['I_a'], label='Series Motor')
axarr[1].plot(series_data['time'], series_data['omega_r'])
axarr[2].plot(series_data['time'], series_data['T_e'])

axarr[0].plot(pm_data['time'], pm_data['I_a'], linestyle='dashed', label='PMDC Motor')
axarr[1].plot(pm_data['time'], pm_data['omega_r'], linestyle='dashed')
axarr[2].plot(pm_data['time'], pm_data['T_e'], linestyle='dashed')

f.legend()
f.tight_layout()

f.savefig('transient.svg')

#+END_SRC

#+ATTR_LATEX: :placement [H]
#+CAPTION: DC Motor Transient Behavior
[[./transient.svg]]
** Steady State Analysis
*** PMDC Motor
From the simulation, the steady state values are:
#+ATTR_LATEX: :align l | l
| $I_a$      | \SI{0.2019}{\ampere}         |
| $\omega_r$ | \SI{325.28}{\radian/\second} |

For $\omega_r = 0$, $E_a = 0$ so the stall current can be found using
\begin{align*}
\left.I_a\right|_{\omega_r = 0} &= \frac{V_a}{R_A} \\
&= \frac{(\SI{6}{\volt})}{(\SI{7}{\ohm})} \\
&= \SI{0.8571}{\ampere}
\end{align*}

The stall torque can then be found by
\begin{align*}
\left.T_e\right|_{\omega_r = 0} &= k_v I_a \\
&= (\SI{14.1}{\milli\volt\second/\radian})(\SI{0.8571}{\ampere}) \\
&= \SI{12.08}{\milli\newton\meter}
\end{align*}
*** Series Motor
From the simulation, the steady state values are:
#+ATTR_LATEX: :align l | l
| $I_a$      | \SI{0.3524}{\ampere}         |
| $\omega_r$ | \SI{228.49}{\radian/\second} |

For $\omega_r = 0$, $E_a = 0$ so the stall current can be found using
\begin{align*}
\left.I_a\right|_{\omega_r = 0} &= \frac{V_a}{R_A + R_F} \\
&= \frac{(\SI{6}{\volt})}{(\SI{6}{\ohm}) + (\SI{1}{\ohm})} \\
&= \SI{0.8571}{\ampere}
\end{align*}

The stall torque can then be found by
\begin{align*}
\left.T_e\right|_{\omega_r = 0} &= L_{AF} I_a^2 \\
&= (\SI{39.5}{\milli\henry})(\SI{0.8571}{\ampere})^2 \\
&= \SI{29.02}{\milli\newton\meter}
\end{align*}
*** Analysis
The calculated values are higher than the peak values from the simulation.
However, they are relatively correct in that the series motor stall torque is was both simulated and calculated to be highter.

The discrepancy comes from the fact that the calculations take a simplistic approach and don't account for the time it takes for the coils to energize and actually impart a torque on the armature.
The simulation takes this time into account, which means it finds a lower starting torque
